/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shehan Chamudith
 */
public class BillCal extends javax.swing.JFrame {

    /**
     * Creates new form BillCal
     */
    
    private double total ;
    
    public BillCal(String value1, String value2, String value3) {
        initComponents();
        billHeader();
        printTextArea(value1, value2, value3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bil.setColumns(20);
        bil.setRows(5);
        jScrollPane2.setViewportView(bil);
        bil.setEditable(false);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 76, 580, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void billHeader() {
        bil.setText("************************************************************************" + "\n" + "\t" + " LIFE CARE PHARMACY " + "\n" + "\t" + "Contact no:+94412273696" + "\n\t" + "No 06,Uyanwatta,Matara." + "\n" + "************************************************************************" + "\n\n" + bil.getText() + "Bill ID:" + "  " + "0001" + "\n" + "\n" + "" + "Medicine" + " \t\t " + "Qty" + " \t " + "Price" + " \t " + "Sub Total" + " \t " + "Total"+ "\n\n");

    }
    public void printTextArea(String v1, String v2, String v3) {
        
        //total = total + Double.parseDouble(qty.getText()) * Double.parseDouble(unitPrice.getText());
        
        String stotal = Double.toString(total);

        bil.setText(bil.getText() + "" + v1 + "\t\t" + v2 + "\t" + v3 + "\t" + Double.parseDouble(v2) * Double.parseDouble(v3) + "\t" + stotal + "\n");

    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    final String value1 = "Medicine1";
    final String value2 = "2";
    final String value3 = "10";
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillCal(value1, value2, value3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
