/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author Shehan Chamudith
 */
public class logged_admin extends javax.swing.JFrame {

    /**
     * Creates new form logged_admin
     */
    public logged_admin() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        side_pannel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        logo_text = new javax.swing.JLabel();
        welcome_text = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        logged_type = new javax.swing.JLabel();
        database_controls = new javax.swing.JPanel();
        drop_down = new javax.swing.JComboBox<>();
        view_tables = new javax.swing.JButton();
        update_inventory = new javax.swing.JButton();
        update_employees = new javax.swing.JButton();
        bill_button = new javax.swing.JPanel();
        bill = new javax.swing.JButton();
        table_preview = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tables = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory");
        setSize(new java.awt.Dimension(1366, 768));

        side_pannel.setBackground(new java.awt.Color(255, 255, 255));
        side_pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/logo1.jpg"))); // NOI18N
        side_pannel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 140, 160));

        logo_text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/logo2.jpg"))); // NOI18N
        side_pannel.add(logo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 78));

        welcome_text.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        welcome_text.setForeground(new java.awt.Color(38, 38, 38));
        welcome_text.setText("Welcome");
        side_pannel.add(welcome_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 388, 68));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/profile1.jpg"))); // NOI18N
        side_pannel.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1184, 18, -1, -1));

        logged_type.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        logged_type.setText("LOGGED - ADMIN");
        side_pannel.add(logged_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(1148, 124, 173, 20));

        database_controls.setBackground(new java.awt.Color(0, 102, 102));

        drop_down.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drop_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drop_downActionPerformed(evt);
            }
        });

        view_tables.setText("View Table");
        view_tables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_tablesActionPerformed(evt);
            }
        });

        update_inventory.setText("Update Inventory");

        update_employees.setText("Update Employees");

        javax.swing.GroupLayout database_controlsLayout = new javax.swing.GroupLayout(database_controls);
        database_controls.setLayout(database_controlsLayout);
        database_controlsLayout.setHorizontalGroup(
            database_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(database_controlsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(database_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_employees, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(database_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(database_controlsLayout.createSequentialGroup()
                            .addComponent(drop_down, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_tables))
                        .addComponent(update_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        database_controlsLayout.setVerticalGroup(
            database_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(database_controlsLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(database_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drop_down, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_tables))
                .addGap(28, 28, 28)
                .addComponent(update_inventory)
                .addGap(31, 31, 31)
                .addComponent(update_employees)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        bill_button.setBackground(new java.awt.Color(0, 153, 102));

        bill.setText("Bill");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bill_buttonLayout = new javax.swing.GroupLayout(bill_button);
        bill_button.setLayout(bill_buttonLayout);
        bill_buttonLayout.setHorizontalGroup(
            bill_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_buttonLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bill_buttonLayout.setVerticalGroup(
            bill_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_buttonLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        table_preview.setBackground(new java.awt.Color(0, 153, 153));

        tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tables);

        javax.swing.GroupLayout table_previewLayout = new javax.swing.GroupLayout(table_preview);
        table_preview.setLayout(table_previewLayout);
        table_previewLayout.setHorizontalGroup(
            table_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_previewLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        table_previewLayout.setVerticalGroup(
            table_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_previewLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_pannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(table_preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bill_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(database_controls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(side_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(database_controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(bill_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(table_preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drop_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drop_downActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drop_downActionPerformed

    private void view_tablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_tablesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_tablesActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logged_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logged_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logged_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logged_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logged_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton bill;
    private javax.swing.JPanel bill_button;
    private javax.swing.JPanel database_controls;
    private javax.swing.JComboBox<String> drop_down;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logged_type;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo_text;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel side_pannel;
    private javax.swing.JPanel table_preview;
    private javax.swing.JTable tables;
    private javax.swing.JButton update_employees;
    private javax.swing.JButton update_inventory;
    private javax.swing.JButton view_tables;
    private javax.swing.JLabel welcome_text;
    // End of variables declaration//GEN-END:variables
}
