/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author Shehan Chamudith
 */
public class ModifyForm extends javax.swing.JFrame {

    /**
     * Creates new form ModifyForm
     */
    public ModifyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clear1 = new javax.swing.JButton();
        ll1 = new javax.swing.JLabel();
        ll2 = new javax.swing.JLabel();
        ll3 = new javax.swing.JLabel();
        ll4 = new javax.swing.JLabel();
        ll5 = new javax.swing.JLabel();
        ll6 = new javax.swing.JLabel();
        ll7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(692, 534));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/clear.png"))); // NOI18N
        jPanel1.add(clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));
        clear1.setOpaque(false);
        clear1.setContentAreaFilled(false);
        clear1.setBorderPainted(false);

        ll1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ll1.setText("Title 1");
        jPanel1.add(ll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        ll2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ll2.setText("Title 2");
        jPanel1.add(ll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        ll3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ll3.setText("Title 3");
        jPanel1.add(ll3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        ll4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ll4.setText("Title 4");
        jPanel1.add(ll4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        ll5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ll5.setText("Title 5");
        jPanel1.add(ll5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        ll6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ll6.setText("Title 6");
        jPanel1.add(ll6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        ll7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ll7.setText("Title 7");
        jPanel1.add(ll7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/modifying.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(692, 534));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ll1;
    private javax.swing.JLabel ll2;
    private javax.swing.JLabel ll3;
    private javax.swing.JLabel ll4;
    private javax.swing.JLabel ll5;
    private javax.swing.JLabel ll6;
    private javax.swing.JLabel ll7;
    // End of variables declaration//GEN-END:variables
}
